[build-system]
requires = ["hatchling", "hatch-vcs", "build", "twine"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
addopts = [
    "-rsxX",
    "-s",
    "--import-mode=importlib",
    "--log-cli-level=DEBUG",
    '-m not slow and not integration',
]
pythonpath = [".", "src", "tests"]
testpaths = ["tests"]
markers = [
    "flaky: tests that can randomly fail through no change to the code",
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: tests that require external resources",
]

[project]
name = "webshooter-client"
dynamic = ["version"]
authors = [
    { name = "Franz Levin" },
    { name = "Shooter_10000", email = "" },
]
description = "A client for interacting with WebShooter.se."
readme = "README.md"

homepage = "https://github.com/frazz/webshooter"
repository = "https://github.com/frazz/webshooter"
documentation = "https://github.com/frazz/webshooter"

urls.Source = 'https://github.com/frazz/webshooter'

classifiers = [
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Environment :: Console",
]

requires-python = ">=3.10"

dependencies = ["packaging==25.0", "requests==2.32.4", "urwid==2.6.16"]

[project.scripts]
wscli = "webshooter_client.command:main"
webshooter = "webshooter_client.command:main"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
local_scheme = "no-local-version"

[tool.hatch.envs.dev]
dependencies = [
    "pytest==8.4.1",
    "pytest-mock==3.14.1",
    "pytest-sugar==1.0.0",
    "pytest-cov==6.2.1",
    "black==25.1.0",
    "flake8==7.3.0",
    "flake8-pyproject==1.2.3",
]

[tool.black]
line-length = 120
target-version = ['py310']

[tool.flake8]
ignore = ["W503"]
max-line-length = 125
# exclude = tests/*
max-complexity = 10
